dataset_options:
  datasets:
  - alce_asqa_8k
  - alce_asqa_16k
  - alce_asqa_32k
  - alce_asqa_64k
  - alce_qampari_8k
  - alce_qampari_16k
  - alce_qampari_32k
  - alce_qampari_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
