dataset_options:
  datasets:
  - json_kv_256k
  - ruler_niah_mk_2_256k
  - ruler_niah_mv_256k
  - mrcr_8_256k
  - longbenchv2_256k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
