dataset_options:
  input_max_length: 1048576,1048576,1048576,1048576,1048576,1048576,1048576,1048576,1048576
  datasets: json_kv,ruler_niah_mk_2_llama3,ruler_niah_mv_llama3,ruler_niah_mq_llama3,ruler_fwe_llama3,mrcr_4_1048576,mrcr_8_1048576,graphwalk_bfs,graphwalk_parent
  generation_max_length: 100,50,50,100,50,1000,1000,1000,1000
  test_files: data/json_kv/test_k20500_dep6.jsonl,data/ruler_llama3/niah_multikey_2/validation_1048576.jsonl,data/ruler_llama3/niah_multivalue/validation_1048576.jsonl,data/ruler_llama3/niah_multiquery/validation_1048576.jsonl,data/ruler_llama3/fwe/validation_1048576.jsonl,,,data/graphwalk/bfs_k70400.jsonl,data/graphwalk/parent_k70400.jsonl
  demo_files: ',,,,,,,,'
  use_chat_template: false
  max_test_samples: 100
  shots: 2
  stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
