dataset_options:
  datasets:
  - json_kv_32k
  - ruler_niah_mk_2_32k
  - ruler_niah_mv_32k
  - ruler_niah_mq_32k
  - ruler_fwe_32k
  - mrcr_4_32k
  - mrcr_8_32k
  - graphwalk_bfs_dep8_32k
  - graphwalk_parent_32k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
