dataset_options:
  datasets:
  - json_kv_32k
  - ruler_niah_mk_2_32k
  - ruler_niah_mv_32k
  - kilt_nq_32k
  - kilt_popqa_32k
  - msmarco_rerank_psg_32k
  - mrcr_8_32k
  - icl_clinic150_32k
  - icl_nlu_32k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
