dataset_options:
  datasets:
  - json_kv_128k
  - ruler_niah_mk_2_128k
  - ruler_niah_mv_128k
  - kilt_nq_128k
  - kilt_popqa_128k
  - msmarco_rerank_psg_128k
  - mrcr_8_128k
  - icl_clinic150_128k
  - icl_nlu_128k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
