dataset_options:
  input_max_length: 524288,524288,524288,524288,524288,524288
  datasets: json_kv,ruler_niah_mk_2,ruler_niah_mv,mrcr_8_524288,graphwalk_bfs,graphwalk_parent
  generation_max_length: 100,50,50,1000,1000,1000
  test_files: data/json_kv/test_k10250_dep6.jsonl,data/ruler/niah_multikey_2/validation_524288.jsonl,data/ruler/niah_multivalue/validation_524288.jsonl,,data/graphwalk/bfs_k35200.jsonl,data/graphwalk/parent_k35200.jsonl
  demo_files: ',,,,,'
  use_chat_template: false
  max_test_samples: 100
  shots: 2
  stop_new_line: false
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
