dataset_options:
  datasets:
  - icl_trec_coarse_128k
  - icl_trec_fine_128k
  - icl_banking77_128k
  - icl_clinic150_128k
  - icl_nlu_128k
  max_test_samples: 500
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
