dataset_options:
  datasets:
  - icl_trec_coarse_8k
  - icl_trec_coarse_16k
  - icl_trec_coarse_32k
  - icl_trec_coarse_64k
  - icl_trec_fine_8k
  - icl_trec_fine_16k
  - icl_trec_fine_32k
  - icl_trec_fine_64k
  - icl_banking77_8k
  - icl_banking77_16k
  - icl_banking77_32k
  - icl_banking77_64k
  - icl_clinic150_8k
  - icl_clinic150_16k
  - icl_clinic150_32k
  - icl_clinic150_64k
  - icl_nlu_8k
  - icl_nlu_16k
  - icl_nlu_32k
  - icl_nlu_64k
  max_test_samples: 500
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
