dataset_options:
  datasets:
  - narrativeqa_8k
  - narrativeqa_16k
  - narrativeqa_32k
  - narrativeqa_64k
  - infbench_qa_8k
  - infbench_qa_16k
  - infbench_qa_32k
  - infbench_qa_64k
  - infbench_choice_8k
  - infbench_choice_16k
  - infbench_choice_32k
  - infbench_choice_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
