dataset_options:
  datasets:
  - ruler_niah_mk_2_512k
  - ruler_niah_mk_2_1m
  - ruler_niah_mk_3_512k
  - ruler_niah_mk_3_1m
  - ruler_niah_mv_512k
  - ruler_niah_mv_1m
  - json_kv_512k
  - json_kv_1m
  - ruler_qa_1_512k
  - ruler_qa_1_1m
  - ruler_qa_2_512k
  - ruler_qa_2_1m
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
