dataset_options:
  datasets:
  - ruler_niah_mk_2_128k
  - ruler_niah_mk_2_256k
  - ruler_niah_mk_3_128k
  - ruler_niah_mk_3_256k
  - ruler_niah_mv_128k
  - ruler_niah_mv_256k
  - json_kv_128k
  - json_kv_256k
  - ruler_qa_1_128k
  - ruler_qa_1_256k
  - ruler_qa_2_128k
  - ruler_qa_2_256k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
