dataset_options:
  datasets:
  - ruler_niah_mk_2_8k
  - ruler_niah_mk_2_16k
  - ruler_niah_mk_2_32k
  - ruler_niah_mk_2_64k
  - ruler_niah_mk_3_8k
  - ruler_niah_mk_3_16k
  - ruler_niah_mk_3_32k
  - ruler_niah_mk_3_64k
  - ruler_niah_mv_8k
  - ruler_niah_mv_16k
  - ruler_niah_mv_32k
  - ruler_niah_mv_64k
  - json_kv_8k
  - json_kv_16k
  - json_kv_32k
  - json_kv_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
