dataset_options:
  datasets:
  - msmarco_rerank_psg_8k
  - msmarco_rerank_psg_16k
  - msmarco_rerank_psg_32k
  - msmarco_rerank_psg_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
