dataset_options:
  datasets:
  - ruler_niah_s_1_128k
  - ruler_niah_s_2_128k
  - ruler_niah_s_3_128k
  - ruler_niah_mk_1_128k
  - ruler_niah_mk_2_128k
  - ruler_niah_mk_3_128k
  - ruler_niah_mq_128k
  - ruler_niah_mv_128k
  - ruler_cwe_128k
  - ruler_fwe_128k
  - ruler_vt_128k
  - ruler_qa_1_128k
  - ruler_qa_2_128k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
