dataset_options:
  datasets:
  - ruler_niah_s_1_8k
  - ruler_niah_s_1_16k
  - ruler_niah_s_1_32k
  - ruler_niah_s_1_64k
  - ruler_niah_s_2_8k
  - ruler_niah_s_2_16k
  - ruler_niah_s_2_32k
  - ruler_niah_s_2_64k
  - ruler_niah_s_3_8k
  - ruler_niah_s_3_16k
  - ruler_niah_s_3_32k
  - ruler_niah_s_3_64k
  - ruler_niah_mk_1_8k
  - ruler_niah_mk_1_16k
  - ruler_niah_mk_1_32k
  - ruler_niah_mk_1_64k
  - ruler_niah_mk_2_8k
  - ruler_niah_mk_2_16k
  - ruler_niah_mk_2_32k
  - ruler_niah_mk_2_64k
  - ruler_niah_mk_3_8k
  - ruler_niah_mk_3_16k
  - ruler_niah_mk_3_32k
  - ruler_niah_mk_3_64k
  - ruler_niah_mq_8k
  - ruler_niah_mq_16k
  - ruler_niah_mq_32k
  - ruler_niah_mq_64k
  - ruler_niah_mv_8k
  - ruler_niah_mv_16k
  - ruler_niah_mv_32k
  - ruler_niah_mv_64k
  - ruler_cwe_8k
  - ruler_cwe_16k
  - ruler_cwe_32k
  - ruler_cwe_64k
  - ruler_fwe_8k
  - ruler_fwe_16k
  - ruler_fwe_32k
  - ruler_fwe_64k
  - ruler_vt_8k
  - ruler_vt_16k
  - ruler_vt_32k
  - ruler_vt_64k
  - ruler_qa_1_8k
  - ruler_qa_1_16k
  - ruler_qa_1_32k
  - ruler_qa_1_64k
  - ruler_qa_2_8k
  - ruler_qa_2_16k
  - ruler_qa_2_32k
  - ruler_qa_2_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
