dataset_options:
  datasets:
  - infbench_sum_8k
  - infbench_sum_16k
  - infbench_sum_32k
  - infbench_sum_64k
  - multi_lexsum_8k
  - multi_lexsum_16k
  - multi_lexsum_32k
  - multi_lexsum_64k
  max_test_samples: 100
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
