dataset_options:
  datasets:
  - icl_trec_coarse_8k
  - icl_trec_coarse_16k
  - icl_trec_coarse_32k
  - icl_trec_coarse_64k
  max_test_samples: 500
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
